# Generated by Django 4.2.2 on 2023-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucknow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
