# Generated by Django 4.2.2 on 2023-07-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_from', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=12)),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varanasi.call_status')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varanasi.status')),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_type', models.CharField(blank=True, choices=[('DIGITAL MARKETING', 'DIGITAL MARKETING'), ('SOFTWARE', 'SOFTWARE'), ('WEBSITE', 'WEBSITE'), ('MOBILE APP', 'MOBILE APP'), ('GAME', 'GAME'), ('OTHERS', 'OTHERS')], max_length=100, null=True)),
                ('comment', models.TextField()),
                ('follow_up', models.DateTimeField(blank=True, null=True)),
                ('call_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='varanasi.call_status')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varanasi.response')),
            ],
        ),
        migrations.CreateModel(
            name='For_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varanasi.response')),
            ],
        ),
        migrations.CreateModel(
            name='For_Coaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varanasi.response')),
            ],
        ),
    ]
