# Generated by Django 4.2.2 on 2023-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
